"""added order id to list models

Revision ID: a0cae05a82f9
Revises: 
Create Date: 2025-05-01 12:41:14.216104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0cae05a82f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('footer', schema=None) as batch_op:
        batch_op.alter_column('linkedin',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('github',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('twitter',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    with op.batch_alter_table('highlight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(),server_default='0', nullable=False))

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(),server_default='0', nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('is_additional',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(),server_default='0', nullable=False))
        batch_op.alter_column('linkedin',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('github',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    with op.batch_alter_table('why_choose', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(),server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('why_choose', schema=None) as batch_op:
        batch_op.drop_column('order_id')

    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.alter_column('github',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('linkedin',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('order_id')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('is_additional',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('icon',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('order_id')

    with op.batch_alter_table('highlight', schema=None) as batch_op:
        batch_op.drop_column('order_id')

    with op.batch_alter_table('footer', schema=None) as batch_op:
        batch_op.alter_column('twitter',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('github',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('linkedin',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
